### ISSUE TITLE
Upload to pypi

### ISSUE THREAD

**Issue by Jellby** [mstuttgart/pynocchio#90]
Just a suggestion: upload the package to pypi, so it's installable with `pip`. It might need renaming, since https://pypi.org/project/pynocchio/ is something else.

**Comment by mstuttgart** [comment]
Hi @Jellby pynocchio is a desktop app. it is not practical to install it using pip.

**Comment by Jellby** [comment]
It might not be ideal for everyone, but it could be an option for some. There are no big or complex requirements, other than PyQt.

**Comment by mstuttgart** [comment]
You need to install others packages tools to use Pynocchio that pip not can install, not only PyQT. The more pratical mode that I find is using a PyInstaller.
 
Develop new features or install options to Pynocchio not is my focus in this moment. Maybe, in the future.
