### ISSUE TITLE
Czech lozalization file

### ISSUE THREAD

**Issue by pafri** [mstuttgart/pynocchio#93]
Pynocchio translated into Czech. File attached. Greetings.

[Pynocchio_cs_CZ.zip](https://github.com/mstuttgart/pynocchio/files/3461467/Pynocchio_cs_CZ.zip)

**Comment by mstuttgart** [comment]
@pafri thanks! Please, can you create a PR to add this translation? You can add the file in this folder: https://github.com/mstuttgart/pynocchio/tree/develop/i18n

**Comment by mstuttgart** [comment]
@pafri I add you translation in next release. Thanks
