### ISSUE TITLE
Translations not updated

### ISSUE THREAD

**Issue by Jellby** [mstuttgart/pynocchio#95]
Prior to version 3 I updated the Spanish translation file `i18n/es.ts`, but the actual resource file (`pynocchio/locale/es.qm`) was not updated.

I could do it, but maybe you want to re-generate for all languages. And update the version number in `data/others/about.html`. And fix or figure out why the translated version of this file that I provided is not being used.

**Comment by mstuttgart** [comment]
I will have a look. I will look.

**Comment by mstuttgart** [comment]
@Jellby new release with translations updated: https://github.com/mstuttgart/pynocchio/releases/tag/3.1.0

**Comment by Jellby** [comment]
Thank you, but the "About" dialog still says 2.2.0 (and it's not translated).

**Comment by mstuttgart** [comment]
Hum... I compiled all translation file. I will have a look. thanks
